steps:
  # Create the .env file
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "NEXT_PUBLIC_HCI_API_URL=${_NEXT_PUBLIC_HCI_API_URL}" > .env.production && \
        echo "CAPTCHA_V3_SECRET_KEY=${_CAPTCHA_V3_SECRET_KEY}" >> .env.production && \
        echo "NEXT_PUBLIC_CAPTCHA_V3_SITE_KEY=${_NEXT_PUBLIC_CAPTCHA_V3_SITE_KEY}" >> .env.production && \
        echo "GOOGGLE_ANALYTICS_ID=${_GOOGGLE_ANALYTICS_ID}" >> .env.production && \
        echo "GOOGLE_TAG_MANAGER_ID=${_GOOGLE_TAG_MANAGER_ID}" >> .env.production && \
        echo "HOTJAR_ID=${_HOTJAR_ID}" >> .env.production && \
        echo 'NEXT_PUBLIC_URL_PROVIDER="https://sso.acesso.gov.br"' >> .env.production && \
        echo 'NEXT_PUBLIC_URL_SERVICE="https://treinamento.hci.rio.gov.br/"' >> .env.production && \
        echo 'NEXT_PUBLIC_REDIRECT_PATH="/auth/sso/callback"' >> .env.production && \
        echo 'NEXT_PUBLIC_SCOPES="openid+email+phone+profile"' >> .env.production && \
        echo "CLIENT_ID=${_CLIENT_ID}" >> .env.production && \
        echo "SECRET=${_SECRET}" >> .env.production
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hci:training-$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/hci:training-$COMMIT_SHA"]
  # Kustomize: set the image in the kustomization.yaml file
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/training"
    entrypoint: "kustomize"
    args:
      - "edit"
      - "set"
      - "image"
      - "gcr.io/project-id/hci=gcr.io/$PROJECT_ID/hci:training-$COMMIT_SHA"
  # Kustomize: apply the kustomization.yaml file
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/training"
    entrypoint: "kustomize"
    args: ["build", ".", "-o", "training.yaml"]
  # Deploy the application to the GKE cluster
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/training"
    args:
      - "run"
      - "--filename=training.yaml"
      - "--location=us-central1"
      - "--cluster=datario"
      - "--project=datario"

images:
  - "gcr.io/$PROJECT_ID/hci:training-$COMMIT_SHA"